<?php
/**
 * Content loading, tokens, partials and icons.
 */
defined( 'ABSPATH' ) || exit;

/** Full content export generated by site/build.mjs. */
function o1g_content(): array {
	static $c = null;
	if ( $c === null ) {
		$c = json_decode( (string) file_get_contents( O1G_DIR . '/inc/content.json' ), true ) ?: [];
	}
	return $c;
}

function o1g_icons(): array {
	static $i = null;
	if ( $i === null ) { $i = json_decode( (string) file_get_contents( O1G_DIR . '/inc/icons.json' ), true ) ?: []; }
	return $i;
}
function o1g_icon( string $name ): string { return o1g_icons()[ $name ] ?? ''; }

/** Business defaults from content.json, overridable in the Customizer. */
function o1g_defaults(): array {
	$b = o1g_content()['business'] ?? [];
	return [
		'phone'         => $b['phone'] ?? '',
		'phone_raw'     => $b['phoneRaw'] ?? '',
		'whatsapp'      => $b['whatsapp'] ?? '',
		'email'         => $b['email'] ?? get_option( 'admin_email' ),
		'lead_email'    => $b['email'] ?? get_option( 'admin_email' ),
		'street'        => $b['street'] ?? '',
		'city'          => $b['city'] ?? '',
		'state'         => $b['state'] ?? 'FL',
		'zip'           => $b['zip'] ?? '',
		'rating'        => $b['rating']['value'] ?? '4.9',
		'rating_count'  => $b['rating']['count'] ?? '100',
		'facebook'      => $b['social']['facebook'] ?? '',
		'instagram'     => $b['social']['instagram'] ?? '',
		'google'        => $b['social']['google'] ?? '',
		'yelp'          => $b['social']['yelp'] ?? '',
		'gtm_id'        => '',
		'webhook'       => '',
		'license'       => $b['license'] ?? '',
		'founded'       => $b['founded'] ?? '',
		'legal_name'    => $b['legalName'] ?? '',
	];
}

function o1g_opt( string $key ) {
	$d = o1g_defaults();
	$v = get_theme_mod( 'o1g_' . $key, $d[ $key ] ?? '' );
	if ( $key === 'phone_raw' && $v === '' ) { $v = '+1' . preg_replace( '/\D/', '', (string) o1g_opt( 'phone' ) ); }
	return $v;
}

function o1g_form_action(): string { return admin_url( 'admin-post.php?action=o1g_lead' ); }
function o1g_thanks_url(): string {
	$p = get_page_by_path( 'thank-you' );
	return $p ? get_permalink( $p ) : home_url( '/' );
}

/** Replace {{tokens}} in exported partials with live Customizer values. */
function o1g_tokens( string $html ): string {
	$addr = sprintf( '%s, %s, %s %s', o1g_opt( 'street' ), o1g_opt( 'city' ), o1g_opt( 'state' ), o1g_opt( 'zip' ) );
	$map = [
		'{{form_action}}'    => esc_url( o1g_form_action() ),
		'{{theme_uri}}'      => esc_url( O1G_URI ),
		'{{phone}}'          => esc_html( o1g_opt( 'phone' ) ),
		'{{phone_raw}}'      => esc_attr( o1g_opt( 'phone_raw' ) ),
		'{{whatsapp}}'       => esc_attr( o1g_opt( 'whatsapp' ) ),
		'{{email}}'          => esc_html( o1g_opt( 'email' ) ),
		'{{google_url}}'     => esc_url( o1g_opt( 'google' ) ),
		'{{rating}}'         => esc_html( o1g_opt( 'rating' ) ),
		'{{rating_count}}'   => esc_html( o1g_opt( 'rating_count' ) ),
		'{{address_inline}}' => esc_html( $addr ),
		'{{address_q}}'      => rawurlencode( $addr ),
		'{{address_br}}'     => esc_html( o1g_opt( 'street' ) ) . '<br>' . esc_html( o1g_opt( 'city' ) . ', ' . o1g_opt( 'state' ) . ' ' . o1g_opt( 'zip' ) ),
	];
	$html = strtr( $html, $map );
	// Photo slots: <!--IMG:slot--> followed by placeholder markup → Customizer image if set.
	$html = preg_replace_callback( '/<!--IMG:([a-z0-9-]+)-->(<div class="media__ph">.*?<\/div><\/div>|<svg.*?<\/svg>)/s', function ( $m ) {
		$id = (int) get_theme_mod( 'o1g_img_' . str_replace( '-', '_', $m[1] ) );
		if ( $id ) { return wp_get_attachment_image( $id, 'large', false, [ 'loading' => 'lazy', 'alt' => get_post_meta( $id, '_wp_attachment_image_alt', true ) ?: ucwords( str_replace( '-', ' ', $m[1] ) ) ] ); }
		return $m[2];
	}, $html );
	// Make root-relative links work on subdirectory installs.
	$home = untrailingslashit( home_url() );
	if ( parse_url( $home, PHP_URL_PATH ) ) {
		$html = preg_replace( '/(href|src|action)="\/(?!\/)/', '$1="' . $home . '/', $html );
	}
	return $html;
}

/** Render an exported partial by key (e.g. "home", "service-gutter-repair"). */
function o1g_partial( string $key ): string {
	$file = O1G_DIR . '/inc/partials/' . basename( $key ) . '.html';
	if ( ! file_exists( $file ) ) { return ''; }
	return o1g_tokens( (string) file_get_contents( $file ) );
}

function o1g_partial_meta( string $key ): array {
	static $m = null;
	if ( $m === null ) { $m = json_decode( (string) file_get_contents( O1G_DIR . '/inc/partials/_meta.json' ), true ) ?: []; }
	return $m[ $key ] ?? [];
}

/** Which partial does the current page use? Set by the importer, or inferred from slug. */
function o1g_page_partial( $post = null ): string {
	$post = get_post( $post );
	if ( ! $post ) { return ''; }
	$p = get_post_meta( $post->ID, '_o1g_partial', true );
	if ( $p ) { return $p; }
	$slug = $post->post_name;
	$map = [ 'services' => 'services-index', 'service-areas' => 'areas-index', 'about' => 'about', 'contact' => 'contact', 'thank-you' => 'thank-you' ];
	if ( isset( $map[ $slug ] ) ) { return $map[ $slug ]; }
	if ( file_exists( O1G_DIR . "/inc/partials/service-{$slug}.html" ) ) { return "service-{$slug}"; }
	if ( preg_match( '/^gutters-(.+)-fl$/', $slug, $mm ) && file_exists( O1G_DIR . "/inc/partials/city-{$mm[1]}.html" ) ) { return "city-{$mm[1]}"; }
	return '';
}

/** Lead form markup (used on generic pages and blog posts). */
function o1g_lead_form( array $a = [] ): string {
	$c = o1g_content();
	$id = $a['id'] ?? 'quote';
	$title = $a['title'] ?? 'Get Your Free Estimate';
	$sub = $a['sub'] ?? 'Written quote within 24 hours. No pressure, no obligation.';
	$compact = ! empty( $a['compact'] );
	$cities = ''; foreach ( $c['cities'] as $ct ) { $cities .= '<option>' . esc_html( $ct['name'] ) . '</option>'; }
	$services = ''; foreach ( $c['services'] as $s ) { $services .= '<option>' . esc_html( $s['name'] ) . '</option>'; }
	$arrow = o1g_icon( 'arrow' );
	$msg = $compact ? '' : "<div class=\"field\"><label for=\"{$id}-message\">Details (optional)</label><textarea id=\"{$id}-message\" name=\"message\" placeholder=\"Stories, approx. linear feet, problem you're seeing, best time to call…\"></textarea></div>";
	return <<<HTML
<div class="card lead-card" id="{$id}">
  <h3>{$title}</h3>
  <p class="lead-card__sub">{$sub}</p>
  <form class="form" data-lead action="{{form_action}}" method="post" id="{$id}-form">
    <input type="hidden" name="source" value="{$id}">
    <p class="hp"><label>Leave this field empty <input type="text" name="website" tabindex="-1" autocomplete="off"></label></p>
    <div class="form__row form__row--2">
      <div class="field"><label for="{$id}-name">Name</label><input id="{$id}-name" name="name" type="text" autocomplete="name" required><span class="field__error">Please enter your name</span></div>
      <div class="field"><label for="{$id}-phone">Phone</label><input id="{$id}-phone" name="phone" type="tel" autocomplete="tel" inputmode="tel" required><span class="field__error">Enter a 10-digit phone</span></div>
    </div>
    <div class="form__row form__row--2">
      <div class="field"><label for="{$id}-email">Email</label><input id="{$id}-email" name="email" type="email" autocomplete="email" required><span class="field__error">Enter a valid email</span></div>
      <div class="field"><label for="{$id}-city">City</label><select id="{$id}-city" name="city">{$cities}<option>Other (Palm Beach County)</option></select></div>
    </div>
    <div class="field"><label for="{$id}-service">What do you need?</label><select id="{$id}-service" name="service">{$services}<option>Not sure / Inspection</option></select></div>
    {$msg}
    <div class="form__status" role="status" aria-live="polite"></div>
    <button class="btn btn--primary btn--lg btn--block" type="submit">Get My Free Estimate {$arrow}</button>
    <p class="form__fine">Or call/text <a href="tel:{{phone_raw}}">{{phone}}</a>. We reply fast, usually within the hour.</p>
  </form>
</div>
HTML;
}

function o1g_contact_aside(): string {
	$phone = o1g_icon( 'phone' ); $wa = o1g_icon( 'whatsapp' );
	$form = o1g_lead_form( [ 'title' => 'Free Estimate', 'sub' => "We'll call you back within the hour during business hours.", 'compact' => true ] );
	return o1g_tokens( "<aside class=\"aside\">{$form}<div class=\"card\"><h3>Prefer to talk?</h3><p style=\"margin:0 0 12px\"><a class=\"btn btn--navy btn--block\" href=\"tel:{{phone_raw}}\">{$phone} {{phone}}</a></p><p style=\"margin:0\"><a class=\"btn btn--whatsapp btn--block\" href=\"https://wa.me/{{whatsapp}}\" rel=\"noopener\">{$wa} Text us on WhatsApp</a></p></div></aside>" );
}

function o1g_cta_band( string $heading = 'Ready for Gutters That Actually Work?', string $sub = 'Free on-site estimate. Written quote in 24 hours. Most installs done in a single day.' ): string {
	$contact = get_page_by_path( 'contact' ); $url = $contact ? get_permalink( $contact ) : home_url( '/contact/' );
	return o1g_tokens( '<section class="section section--tight"><div class="container"><div class="cta-band reveal"><div><h2>' . esc_html( $heading ) . '</h2><p>' . esc_html( $sub ) . '</p></div><div class="cta-band__actions"><a class="btn btn--primary btn--lg" href="' . esc_url( $url ) . '">Get a Free Estimate ' . o1g_icon( 'arrow' ) . '</a><a class="btn btn--ghost-light btn--lg" href="tel:{{phone_raw}}">' . o1g_icon( 'phone' ) . ' {{phone}}</a></div></div></div></section>' );
}

function o1g_crumbs( array $items ): string {
	$out = '<ol class="crumbs">';
	$n = count( $items );
	foreach ( $items as $i => $c ) {
		$out .= $i < $n - 1 ? '<li><a href="' . esc_url( $c[1] ) . '">' . esc_html( $c[0] ) . '</a></li>' : '<li aria-current="page">' . esc_html( $c[0] ) . '</li>';
	}
	return $out . '</ol>';
}

function o1g_page_hero( string $h1, string $lead = '', string $eyebrow = '', string $crumbs = '', bool $cta = true ): string {
	$html = '<section class="page-hero"><div class="container">' . $crumbs . ( $eyebrow ? '<span class="eyebrow">' . esc_html( $eyebrow ) . '</span>' : '' ) . '<h1>' . esc_html( $h1 ) . '</h1>' . ( $lead ? '<p class="lead">' . wp_kses_post( $lead ) . '</p>' : '' );
	if ( $cta ) { $html .= '<div class="hero__actions"><a class="btn btn--primary btn--lg" href="#quote">Get a Free Estimate ' . o1g_icon( 'arrow' ) . '</a><a class="btn btn--ghost-light btn--lg" href="tel:{{phone_raw}}">' . o1g_icon( 'phone' ) . ' {{phone}}</a></div>'; }
	return o1g_tokens( $html . '</div></section>' );
}
